[cookie]
expiry_days = 1
key = "some_signature_key"
name = "some_cookie_name"

[usernames.zhangsan]
name = "张三"
password = "1234"
logged_in = false
failed_login_attempts = 0

[usernames.lisi]
name = "李四"
password = "4321"
logged_in = false
failed_login_attempts = 0

[usernames.wangwu]
name = "王五"
email = "fjaks@qq.com"
password = "9999"
logged_in = false
failed_login_attempts = 0
